# Get all users.

GET http://localhost:9080/niajee/api/users

###

# Get single character.

GET http://localhost:9080/niajee/api/users/ed6cfb2a-cad7-47dd-9b56-9d1e3c7a4197

###

# Get single user portrait.

GET http://localhost:9080/niajee/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/portrait

###

# Create user portrait.

PUT http://localhost:9080/niajee/api/users/c4a04a73-f6e0-4996-a465-3b85f2ad1ea3/portrait
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="portrait"; filename="bob.png'

< src/main/resources/com/jelinski/niajee/configuration/avatar/bob.png
--boundary--

###

# Get single user portrait.

GET http://localhost:9080/niajee/api/users/c4a04a73-f6e0-4996-a465-3b85f2ad1ea3/portrait

###

# Delete user's portrait.

DELETE http://localhost:9080/niajee/api/users/c4a04a73-f6e0-4996-a465-3b85f2ad1ea3/portrait

###

# Get all motorcycle types

GET http://localhost:9080/niajee/api/motorcycleTypes

###

# Get single motorcycle type

GET http://localhost:9080/niajee/api/motorcycleTypes/47fc4252-9c4e-4b61-8042-05648be14bc0

###

# Create new motorcycle type

PUT http://localhost:9080/niajee/api/motorcycleTypes/8d48d3fb-ffde-4646-bb58-0e59a2909952
Content-Type: application/json

{
  "typeName": "Scooter",
  "description": "Scooters are popular for personal transportation partly due to being more affordable, easy to operate, convenient to park and store. Licensing requirements for scooters are easier and cheaper than for cars in most parts of the world, and insurance is usually cheaper.",
  "ridingPosition": "UPRIGHT"
}

###

# Update existing motorcycle type

PATCH http://localhost:9080/niajee/api/motorcycleTypes/bbb60000-1a7d-45cb-b6ac-3812c8f8eb3d
Content-Type: application/json

{
  "typeName": "Changed",
  "description": "Changed"
}

###

# Delete existing motorcycle type
DELETE http://localhost:9080/niajee/api/motorcycleTypes/8d48d3fb-ffde-4646-bb58-0e59a2909952

###

# Get all motorcycles

GET http://localhost:9080/niajee/api/motorcycles

###

# Get single motorcycle

GET http://localhost:9080/niajee/api/motorcycles/76658188-838c-484a-ab78-5c1316f02609

###

# Get all motorcycle type motorcycles

GET http://localhost:9080/niajee/api/motorcycleTypes/47fc4252-9c4e-4b61-8042-05648be14bc0/motorcycles

###

# Create new motorcycle

PUT http://localhost:9080/niajee/api/motorcycleTypes/8d48d3fb-ffde-4646-bb58-0e59a2909952/motorcycles/76658188-838c-484a-ab78-5c1316f02609
Content-Type: application/json

{
  "name": "Honda CBR 1000RR",
  "horsepower": 200,
  "color": "RED",
  "brand": "HONDA",
  "productionDate": "2017-01-01",
  "price": 60000,
  "weight": 200
}

###

# Update existing motorcycle

PATCH http://localhost:9080/niajee/api/motorcycleTypes/47fc4252-9c4e-4b61-8042-05648be14bc0/motorcycles/d8422238-ce90-4c9b-87ec-cd75f2bb32f3
Content-Type: application/json

{
  "name": "Changed",
  "color": "WHITE",
  "price": 999
}

###

# Delete existing motorcycle

DELETE http://localhost:9080/niajee/api/motorcycles/76658188-838c-484a-ab78-5c1316f02609

###