# Get all users.

// @no-cookie-jar
GET http://localhost:9080/niajee/api/users
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg== #admin:admin
#Authorization: Basic a2V2aW46dXNlcnVzZXI= #kevin:user

###

# Get single user.

// @no-cookie-jar
GET http://localhost:9080/niajee/api/users/ed6cfb2a-cad7-47dd-9b56-9d1e3c7a4197
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg== #admin:admin

###

# Get single user portrait.

// @no-cookie-jar
GET http://localhost:9080/niajee/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/portrait
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg== #admin:admin

###

# Create user portrait.

// @no-cookie-jar
PUT http://localhost:9080/niajee/api/users/c4a04a73-f6e0-4996-a465-3b85f2ad1ea3/portrait
Content-Type: multipart/form-data; boundary=boundary
Authorization: Basic Ym9iOnVzZXJ1c2Vy #bob:user


--boundary
Content-Disposition: form-data; name="portrait"; filename="bob.png'

< src/main/resources/com/jelinski/niajee/configuration/avatar/bob.png
--boundary--

###

# Get single user portrait.

// @no-cookie-jar
GET http://localhost:9080/niajee/api/users/c4a04a73-f6e0-4996-a465-3b85f2ad1ea3/portrait
Authorization: Basic Ym9iOnVzZXJ1c2Vy #bob:user
#Authorization: Basic a2V2aW46dXNlcnVzZXI= #kevin:user

###

# Delete user's portrait.

// @no-cookie-jar
DELETE http://localhost:9080/niajee/api/users/c4a04a73-f6e0-4996-a465-3b85f2ad1ea3/portrait
#Authorization: Basic a2V2aW46dXNlcnVzZXI= #kevin:user
Authorization: Basic Ym9iOnVzZXJ1c2Vy #bob:user
###

# Register new user.

// @no-cookie-jar
PUT http://localhost:9080/niajee/api/users/71034458-f603-4f87-abd6-27b80ee52f1c
Content-Type: application/json
#Authorization: Basic bWFyazoxMjM0NTY3OA== #mark:user

{
  "login": "mark",
  "name": "Mark",
  "surname": "Zuckerberg",
  "birthDate": "1984-05-14",
  "email": "mark.zuckerber@facebook.com",
  "password": "12345678"
}

###

# Get all motorcycle types

// @no-cookie-jar
GET http://localhost:9080/niajee/api/motorcycleTypes
Authorization: Basic a2V2aW46dXNlcnVzZXI= #kevin:user
#Authorization: Basic YWRtaW46YWRtaW5hZG1pbg== #admin:admin

###

# Get single motorcycle type

// @no-cookie-jar
GET http://localhost:9080/niajee/api/motorcycleTypes/47fc4252-9c4e-4b61-8042-05648be14bc0
Authorization: Basic a2V2aW46dXNlcnVzZXI= #kevin:user

###

# Create new motorcycle type

// @no-cookie-jar
PUT http://localhost:9080/niajee/api/motorcycleTypes/8d48d3fb-ffde-4646-bb58-0e59a2909952
Content-Type: application/json
Authorization: Basic a2V2aW46dXNlcnVzZXI= #kevin:user
#Authorization: Basic YWRtaW46YWRtaW5hZG1pbg== #admin:admin

{
  "typeName": "Scooter",
  "description": "Scooters are popular for personal transportation partly due to being more affordable, easy to operate, convenient to park and store. Licensing requirements for scooters are easier and cheaper than for cars in most parts of the world, and insurance is usually cheaper.",
  "ridingPosition": "UPRIGHT"
}

###

# Update existing motorcycle type

// @no-cookie-jar
PATCH http://localhost:9080/niajee/api/motorcycleTypes/bbb60000-1a7d-45cb-b6ac-3812c8f8eb3d
Content-Type: application/json
Authorization: Basic a2V2aW46dXNlcnVzZXI= #kevin:user
#Authorization: Basic YWRtaW46YWRtaW5hZG1pbg== #admin:admin

{
  "typeName": "Changed",
  "description": "Changed"
}

###

# Delete existing motorcycle type

// @no-cookie-jar
DELETE http://localhost:9080/niajee/api/motorcycleTypes/8d48d3fb-ffde-4646-bb58-0e59a2909952
Authorization: Basic a2V2aW46dXNlcnVzZXI= #kevin:user
#Authorization: Basic YWRtaW46YWRtaW5hZG1pbg== #admin:admin

###

# Get all motorcycles

// @no-cookie-jar
GET http://localhost:9080/niajee/api/motorcycles
#Authorization: Basic a2V2aW46dXNlcnVzZXI= #kevin:user
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg== #admin:admin
#Authorization: Basic bWFyazoxMjM0NTY3OA== #mark:user

###

# Get single motorcycle

// @no-cookie-jar
GET http://localhost:9080/niajee/api/motorcycles/d8422238-ce90-4c9b-87ec-cd75f2bb32f3
Authorization: Basic YWxpY2U6dXNlcnVzZXI= #alice:user
#Authorization: Basic a2V2aW46dXNlcnVzZXI= #kevin:user

###

# Get all motorcycle type motorcycles

// @no-cookie-jar
GET http://localhost:9080/niajee/api/motorcycleTypes/47fc4252-9c4e-4b61-8042-05648be14bc0/motorcycles
#Authorization: Basic YWRtaW46YWRtaW5hZG1pbg== #admin:admin
#Authorization: Basic bWFyazoxMjM0NTY3OA== #mark:user

###

# Create new motorcycle

// @no-cookie-jar
PUT http://localhost:9080/niajee/api/motorcycleTypes/47fc4252-9c4e-4b61-8042-05648be14bc0/motorcycles/76658188-838c-484a-ab78-5c1316f02609
Content-Type: application/json
#Authorization: Basic a2V2aW46dXNlcnVzZXI= #kevin:user
Authorization: Basic bWFyazoxMjM0NTY3OA== #mark:user

{
  "name": "Honda CBR 1000R",
  "horsepower": 200,
  "color": "RED",
  "brand": "HONDA",
  "productionDate": "2017-01-01",
  "price": 60000,
  "weight": 200
}

###

# Update existing motorcycle

// @no-cookie-jar
PATCH http://localhost:9080/niajee/api/motorcycleTypes/47fc4252-9c4e-4b61-8042-05648be14bc0/motorcycles/d8422238-ce90-4c9b-87ec-cd75f2bb32f3
Content-Type: application/json
#Authorization: Basic a2V2aW46dXNlcnVzZXI= #kevin:user
Authorization: Basic YWxpY2U6dXNlcnVzZXI= #alice:user

{
  "name": "Changed",
  "color": "WHITE",
  "price": 999
}

###

# Delete existing motorcycle

// @no-cookie-jar
DELETE http://localhost:9080/niajee/api/motorcycles/76658188-838c-484a-ab78-5c1316f02609
Authorization: Basic a2V2aW46dXNlcnVzZXI= #kevin:user
#Authorization: Basic YWxpY2U6dXNlcnVzZXI= #alice:user
#Authorization: Basic YWRtaW46YWRtaW5hZG1pbg== #admin:admin

###